/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_dlg_about (void);
GtkWidget* create_dlg_exit (void);
GtkWidget* create_dlg_message (void);
GtkWidget* create_dlg_distribuzione (void);
GtkWidget* create_dlg_work (void);
GtkWidget* create_dlg_edit_ordine (void);
GtkWidget* create_dlg_select (void);
GtkWidget* create_dlg_config (void);
GtkWidget* create_dlg_edit_collo (void);
GtkWidget* create_dlg_expand (void);
GtkWidget* create_dlg_import (void);
GtkWidget* create_dlg_app_error (void);
GtkWidget* create_dlg_import_file (void);
GtkWidget* create_dlg_import_ordini (void);
GtkWidget* create_dlg_export (void);
GtkWidget* create_dlg_set_ordini (void);
GtkWidget* create_dlg_reset_settore (void);
GtkWidget* create_dlg_lancio_distribuzioni (void);
GtkWidget* create_dlg_carico_settori (void);
GtkWidget* create_dlg_export_message (void);
GtkWidget* create_dlg_stat_prelievo (void);
GtkWidget* create_dlg_test_ios (void);
GtkWidget* create_dlg_storico (void);
GtkWidget* create_dlg_stampa (void);
GtkWidget* create_dlg_set_prio (void);
GtkWidget* create_dlg_operatori (void);
GtkWidget* create_dlg_lancio_consuntivo (void);
GtkWidget* create_dlg_lancio_evasione (void);
GtkWidget* create_dlg_prodotti (void);
GtkWidget* create_dlg_start_impianto (void);
GtkWidget* create_dlg_stop_impianto (void);
GtkWidget* create_dlg_select_elaborazione (void);
GtkWidget* create_dlg_prodotti_pericolosi (void);
