/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dlg_exit (void);
GtkWidget* create_dlg_message (void);
GtkWidget* create_dlg_info (void);
GtkWidget* create_dlg_config (void);
GtkWidget* create_dlg_app_error (void);
GtkWidget* create_main_window (void);
GtkWidget* create_dlg_edit_ordine (void);
GtkWidget* create_dlg_edit_collo (void);
GtkWidget* create_dlg_barcode (void);
GtkWidget* create_dlg_trace (void);
GtkWidget* create_dlg_add_var (void);
GtkWidget* create_dlg_force_var (void);
GtkWidget* create_dlg_debug_var (void);
GtkWidget* create_dlg_plc_error (void);
GtkWidget* create_dlg_fine_linea (void);
GtkWidget* create_dlg_stampa_ordine (void);
GtkWidget* create_dlg_aggiungi_collo (void);
GtkWidget* create_dlg_elimina_collo (void);
GtkWidget* create_dlg_scarto (void);
