# ------------------------------------
# Makefile per WELLA - Easypicking 3.0
# ------------------------------------
# Copyright CNI srl 1995

all:
	(cd pmx_msq; make all)

clean:
	(cd pmx_msq; make clean)
