/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_dlg_about (void);
GtkWidget* create_dlg_exit (void);
GtkWidget* create_dlg_message (void);
GtkWidget* create_dlg_edit_ordine (void);
GtkWidget* create_dlg_config (void);
GtkWidget* create_dlg_edit_collo (void);
GtkWidget* create_dlg_app_error (void);
GtkWidget* create_dlg_stampa_ordine (void);
