/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dlg_about (void)
{
  GtkWidget *dlg_about;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *frame6;
  GtkWidget *hbox183;
  GtkWidget *image8;
  GtkWidget *image11;
  GtkWidget *hbox182;
  GtkWidget *image9;
  GtkWidget *image10;
  GtkWidget *frame1;
  GtkWidget *vbox3;
  GtkWidget *table25;
  GtkWidget *label646;
  GtkWidget *label647;
  GtkWidget *label648;
  GtkWidget *frame230;
  GtkWidget *lb_version;
  GtkWidget *frame231;
  GtkWidget *lb_customer;
  GtkWidget *frame232;
  GtkWidget *lb_rcsid;
  GtkWidget *label1223;
  GtkWidget *label1224;
  GtkWidget *frame534;
  GtkWidget *lb_authors;
  GtkWidget *frame535;
  GtkWidget *lb_copyright;
  GtkWidget *dialog_action_area1;
  GtkWidget *pb_close;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  dlg_about = gtk_dialog_new ();
  gtk_widget_set_name (dlg_about, "dlg_about");
  gtk_window_set_title (GTK_WINDOW (dlg_about), "About");
  gtk_window_set_position (GTK_WINDOW (dlg_about), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (dlg_about), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dlg_about), FALSE);

  dialog_vbox1 = GTK_DIALOG (dlg_about)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox2, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 5);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame6, "frame6");
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (hbox1), frame6, TRUE, TRUE, 0);

  hbox183 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox183, "hbox183");
  gtk_widget_show (hbox183);
  gtk_container_add (GTK_CONTAINER (frame6), hbox183);

  image8 = create_pixmap (dlg_about, "AEL-GLOSSY-small.png");
  gtk_widget_set_name (image8, "image8");
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox183), image8, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (image8), 2, 0);

  image11 = create_pixmap (dlg_about, "easy-picking.png");
  gtk_widget_set_name (image11, "image11");
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox183), image11, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (image11), 2, 0);

  hbox182 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox182, "hbox182");
  gtk_widget_show (hbox182);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox182, TRUE, TRUE, 0);

  image9 = create_pixmap (dlg_about, "gnome-64.png");
  gtk_widget_set_name (image9, "image9");
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox182), image9, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (image9), 2, 0);

  image10 = create_pixmap (dlg_about, "postgresql.png");
  gtk_widget_set_name (image10, "image10");
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox182), image10, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (image10), 2, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox2), frame1, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);
  gtk_frame_set_label_align (GTK_FRAME (frame1), 0.5, 0.5);

  vbox3 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame1), vbox3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 5);

  table25 = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (table25, "table25");
  gtk_widget_show (table25);
  gtk_box_pack_start (GTK_BOX (vbox3), table25, FALSE, FALSE, 2);
  gtk_table_set_row_spacings (GTK_TABLE (table25), 2);

  label646 = gtk_label_new ("Version");
  gtk_widget_set_name (label646, "label646");
  gtk_widget_show (label646);
  gtk_table_attach (GTK_TABLE (table25), label646, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label646), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label646), 0, 0.5);

  label647 = gtk_label_new ("Customer Name");
  gtk_widget_set_name (label647, "label647");
  gtk_widget_show (label647);
  gtk_table_attach (GTK_TABLE (table25), label647, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label647), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label647), 0, 0.5);

  label648 = gtk_label_new ("RCSID String");
  gtk_widget_set_name (label648, "label648");
  gtk_widget_show (label648);
  gtk_table_attach (GTK_TABLE (table25), label648, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label648), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label648), 0, 0.5);

  frame230 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame230, "frame230");
  gtk_widget_show (frame230);
  gtk_table_attach (GTK_TABLE (table25), frame230, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_version = gtk_label_new ("");
  gtk_widget_set_name (lb_version, "lb_version");
  gtk_widget_show (lb_version);
  gtk_container_add (GTK_CONTAINER (frame230), lb_version);
  gtk_label_set_justify (GTK_LABEL (lb_version), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_version), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_version), 2, 0);

  frame231 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame231, "frame231");
  gtk_widget_show (frame231);
  gtk_table_attach (GTK_TABLE (table25), frame231, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_customer = gtk_label_new ("");
  gtk_widget_set_name (lb_customer, "lb_customer");
  gtk_widget_show (lb_customer);
  gtk_container_add (GTK_CONTAINER (frame231), lb_customer);
  gtk_label_set_justify (GTK_LABEL (lb_customer), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_customer), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_customer), 2, 0);

  frame232 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame232, "frame232");
  gtk_widget_show (frame232);
  gtk_table_attach (GTK_TABLE (table25), frame232, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_rcsid = gtk_label_new ("");
  gtk_widget_set_name (lb_rcsid, "lb_rcsid");
  gtk_widget_show (lb_rcsid);
  gtk_container_add (GTK_CONTAINER (frame232), lb_rcsid);
  gtk_label_set_justify (GTK_LABEL (lb_rcsid), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_rcsid), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_rcsid), 2, 0);

  label1223 = gtk_label_new ("Authors");
  gtk_widget_set_name (label1223, "label1223");
  gtk_widget_show (label1223);
  gtk_table_attach (GTK_TABLE (table25), label1223, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1223), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1223), 0, 0.5);

  label1224 = gtk_label_new ("Copyright");
  gtk_widget_set_name (label1224, "label1224");
  gtk_widget_show (label1224);
  gtk_table_attach (GTK_TABLE (table25), label1224, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1224), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1224), 0, 0.5);

  frame534 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame534, "frame534");
  gtk_widget_show (frame534);
  gtk_table_attach (GTK_TABLE (table25), frame534, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_authors = gtk_label_new ("");
  gtk_widget_set_name (lb_authors, "lb_authors");
  gtk_widget_show (lb_authors);
  gtk_container_add (GTK_CONTAINER (frame534), lb_authors);
  gtk_label_set_justify (GTK_LABEL (lb_authors), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_authors), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_authors), 2, 0);

  frame535 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame535, "frame535");
  gtk_widget_show (frame535);
  gtk_table_attach (GTK_TABLE (table25), frame535, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_copyright = gtk_label_new ("");
  gtk_widget_set_name (lb_copyright, "lb_copyright");
  gtk_widget_show (lb_copyright);
  gtk_container_add (GTK_CONTAINER (frame535), lb_copyright);
  gtk_label_set_justify (GTK_LABEL (lb_copyright), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_copyright), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_copyright), 2, 0);

  dialog_action_area1 = GTK_DIALOG (dlg_about)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);

  pb_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (pb_close, "pb_close");
  gtk_widget_show (pb_close);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlg_about), pb_close, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (pb_close, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (pb_close, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_about, dlg_about, "dlg_about");
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_about, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dlg_about, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (dlg_about, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (dlg_about, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (dlg_about, hbox183, "hbox183");
  GLADE_HOOKUP_OBJECT (dlg_about, image8, "image8");
  GLADE_HOOKUP_OBJECT (dlg_about, image11, "image11");
  GLADE_HOOKUP_OBJECT (dlg_about, hbox182, "hbox182");
  GLADE_HOOKUP_OBJECT (dlg_about, image9, "image9");
  GLADE_HOOKUP_OBJECT (dlg_about, image10, "image10");
  GLADE_HOOKUP_OBJECT (dlg_about, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (dlg_about, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (dlg_about, table25, "table25");
  GLADE_HOOKUP_OBJECT (dlg_about, label646, "label646");
  GLADE_HOOKUP_OBJECT (dlg_about, label647, "label647");
  GLADE_HOOKUP_OBJECT (dlg_about, label648, "label648");
  GLADE_HOOKUP_OBJECT (dlg_about, frame230, "frame230");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_version, "lb_version");
  GLADE_HOOKUP_OBJECT (dlg_about, frame231, "frame231");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_customer, "lb_customer");
  GLADE_HOOKUP_OBJECT (dlg_about, frame232, "frame232");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_rcsid, "lb_rcsid");
  GLADE_HOOKUP_OBJECT (dlg_about, label1223, "label1223");
  GLADE_HOOKUP_OBJECT (dlg_about, label1224, "label1224");
  GLADE_HOOKUP_OBJECT (dlg_about, frame534, "frame534");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_authors, "lb_authors");
  GLADE_HOOKUP_OBJECT (dlg_about, frame535, "frame535");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_copyright, "lb_copyright");
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_about, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dlg_about, pb_close, "pb_close");

  gtk_window_add_accel_group (GTK_WINDOW (dlg_about), accel_group);

  return dlg_about;
}

GtkWidget*
create_dlg_config (void)
{
  GtkWidget *dlg_config;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox63;
  GtkWidget *frame226;
  GtkWidget *vbox331;
  GtkWidget *table26;
  GtkWidget *label642;
  GtkObject *sb_debug_version_adj;
  GtkWidget *sb_debug_version;
  GtkWidget *entry_printer;
  GtkObject *sb_ora_inizio_adj;
  GtkWidget *sb_ora_inizio;
  GtkObject *sb_ora_fine_adj;
  GtkWidget *sb_ora_fine;
  GtkObject *sb_numero_operatori_adj;
  GtkWidget *sb_numero_operatori;
  GtkWidget *label289;
  GtkWidget *label1230;
  GtkWidget *label1231;
  GtkWidget *label1232;
  GtkWidget *label1225;
  GtkWidget *frame164;
  GtkWidget *table22;
  GtkWidget *entry_data_path;
  GtkWidget *entry_print_path;
  GtkWidget *label543;
  GtkWidget *label827;
  GtkWidget *label1226;
  GtkWidget *frame156;
  GtkWidget *table11;
  GtkWidget *entry_db_host;
  GtkWidget *entry_db_port;
  GtkWidget *entry_db_name;
  GtkWidget *lb_pghost;
  GtkWidget *lb_pgport;
  GtkWidget *lb_pgdatabase;
  GtkWidget *label1227;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton1;
  GtkWidget *applybutton1;
  GtkWidget *pb_close;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  dlg_config = gtk_dialog_new ();
  gtk_widget_set_name (dlg_config, "dlg_config");
  gtk_window_set_title (GTK_WINDOW (dlg_config), "Configurazione");
  gtk_window_set_position (GTK_WINDOW (dlg_config), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (dlg_config), TRUE);

  dialog_vbox2 = GTK_DIALOG (dlg_config)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_widget_show (dialog_vbox2);

  vbox63 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox63, "vbox63");
  gtk_widget_show (vbox63);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox63, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox63), 5);

  frame226 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame226, "frame226");
  gtk_widget_show (frame226);
  gtk_box_pack_start (GTK_BOX (vbox63), frame226, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame226), 5);

  vbox331 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox331, "vbox331");
  gtk_widget_show (vbox331);
  gtk_container_add (GTK_CONTAINER (frame226), vbox331);

  table26 = gtk_table_new (5, 2, TRUE);
  gtk_widget_set_name (table26, "table26");
  gtk_widget_show (table26);
  gtk_box_pack_start (GTK_BOX (vbox331), table26, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table26), 5);

  label642 = gtk_label_new_with_mnemonic ("_Debug Version");
  gtk_widget_set_name (label642, "label642");
  gtk_widget_show (label642);
  gtk_table_attach (GTK_TABLE (table26), label642, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label642), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label642), 0, 0.5);

  sb_debug_version_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sb_debug_version = gtk_spin_button_new (GTK_ADJUSTMENT (sb_debug_version_adj), 1, 0);
  gtk_widget_set_name (sb_debug_version, "sb_debug_version");
  gtk_widget_show (sb_debug_version);
  gtk_table_attach (GTK_TABLE (table26), sb_debug_version, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_printer = gtk_entry_new ();
  gtk_widget_set_name (entry_printer, "entry_printer");
  gtk_widget_show (entry_printer);
  gtk_table_attach (GTK_TABLE (table26), entry_printer, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  sb_ora_inizio_adj = gtk_adjustment_new (1, 0, 24, 1, 10, 10);
  sb_ora_inizio = gtk_spin_button_new (GTK_ADJUSTMENT (sb_ora_inizio_adj), 1, 0);
  gtk_widget_set_name (sb_ora_inizio, "sb_ora_inizio");
  gtk_widget_show (sb_ora_inizio);
  gtk_table_attach (GTK_TABLE (table26), sb_ora_inizio, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  sb_ora_fine_adj = gtk_adjustment_new (1, 0, 24, 1, 10, 10);
  sb_ora_fine = gtk_spin_button_new (GTK_ADJUSTMENT (sb_ora_fine_adj), 1, 0);
  gtk_widget_set_name (sb_ora_fine, "sb_ora_fine");
  gtk_widget_show (sb_ora_fine);
  gtk_table_attach (GTK_TABLE (table26), sb_ora_fine, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  sb_numero_operatori_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  sb_numero_operatori = gtk_spin_button_new (GTK_ADJUSTMENT (sb_numero_operatori_adj), 1, 0);
  gtk_widget_set_name (sb_numero_operatori, "sb_numero_operatori");
  gtk_widget_show (sb_numero_operatori);
  gtk_table_attach (GTK_TABLE (table26), sb_numero_operatori, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label289 = gtk_label_new_with_mnemonic ("Coda di _stampa");
  gtk_widget_set_name (label289, "label289");
  gtk_widget_show (label289);
  gtk_table_attach (GTK_TABLE (table26), label289, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label289), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label289), 0, 0.5);

  label1230 = gtk_label_new_with_mnemonic ("Ora _inizio statistica");
  gtk_widget_set_name (label1230, "label1230");
  gtk_widget_show (label1230);
  gtk_table_attach (GTK_TABLE (table26), label1230, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1230), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1230), 0, 0.5);

  label1231 = gtk_label_new_with_mnemonic ("Ora _fine  statistica");
  gtk_widget_set_name (label1231, "label1231");
  gtk_widget_show (label1231);
  gtk_table_attach (GTK_TABLE (table26), label1231, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1231), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1231), 0, 0.5);

  label1232 = gtk_label_new_with_mnemonic ("Numero Operatori");
  gtk_widget_set_name (label1232, "label1232");
  gtk_widget_show (label1232);
  gtk_table_attach (GTK_TABLE (table26), label1232, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1232), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1232), 0, 0.5);

  label1225 = gtk_label_new ("Generale");
  gtk_widget_set_name (label1225, "label1225");
  gtk_widget_show (label1225);
  gtk_frame_set_label_widget (GTK_FRAME (frame226), label1225);

  frame164 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame164, "frame164");
  gtk_widget_show (frame164);
  gtk_box_pack_start (GTK_BOX (vbox63), frame164, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame164), 5);

  table22 = gtk_table_new (2, 2, TRUE);
  gtk_widget_set_name (table22, "table22");
  gtk_widget_show (table22);
  gtk_container_add (GTK_CONTAINER (frame164), table22);
  gtk_container_set_border_width (GTK_CONTAINER (table22), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table22), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table22), 3);

  entry_data_path = gtk_entry_new ();
  gtk_widget_set_name (entry_data_path, "entry_data_path");
  gtk_widget_show (entry_data_path);
  gtk_table_attach (GTK_TABLE (table22), entry_data_path, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_print_path = gtk_entry_new ();
  gtk_widget_set_name (entry_print_path, "entry_print_path");
  gtk_widget_show (entry_print_path);
  gtk_table_attach (GTK_TABLE (table22), entry_print_path, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label543 = gtk_label_new_with_mnemonic ("Dati di _configurazione");
  gtk_widget_set_name (label543, "label543");
  gtk_widget_show (label543);
  gtk_table_attach (GTK_TABLE (table22), label543, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label543), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label543), 0, 0.5);

  label827 = gtk_label_new_with_mnemonic ("Sta_mpe");
  gtk_widget_set_name (label827, "label827");
  gtk_widget_show (label827);
  gtk_table_attach (GTK_TABLE (table22), label827, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label827), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label827), 0, 0.5);

  label1226 = gtk_label_new ("Indirizzi");
  gtk_widget_set_name (label1226, "label1226");
  gtk_widget_show (label1226);
  gtk_frame_set_label_widget (GTK_FRAME (frame164), label1226);

  frame156 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame156, "frame156");
  gtk_widget_show (frame156);
  gtk_box_pack_start (GTK_BOX (vbox63), frame156, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame156), 5);

  table11 = gtk_table_new (3, 2, TRUE);
  gtk_widget_set_name (table11, "table11");
  gtk_widget_show (table11);
  gtk_container_add (GTK_CONTAINER (frame156), table11);
  gtk_container_set_border_width (GTK_CONTAINER (table11), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table11), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table11), 3);

  entry_db_host = gtk_entry_new ();
  gtk_widget_set_name (entry_db_host, "entry_db_host");
  gtk_widget_show (entry_db_host);
  gtk_table_attach (GTK_TABLE (table11), entry_db_host, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_db_port = gtk_entry_new ();
  gtk_widget_set_name (entry_db_port, "entry_db_port");
  gtk_widget_show (entry_db_port);
  gtk_table_attach (GTK_TABLE (table11), entry_db_port, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_db_name = gtk_entry_new ();
  gtk_widget_set_name (entry_db_name, "entry_db_name");
  gtk_widget_show (entry_db_name);
  gtk_table_attach (GTK_TABLE (table11), entry_db_name, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_pghost = gtk_label_new_with_mnemonic ("Nome _Host");
  gtk_widget_set_name (lb_pghost, "lb_pghost");
  gtk_widget_show (lb_pghost);
  gtk_table_attach (GTK_TABLE (table11), lb_pghost, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lb_pghost), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_pghost), 0, 0.5);

  lb_pgport = gtk_label_new_with_mnemonic ("Porta _TCP/IP");
  gtk_widget_set_name (lb_pgport, "lb_pgport");
  gtk_widget_show (lb_pgport);
  gtk_table_attach (GTK_TABLE (table11), lb_pgport, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lb_pgport), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_pgport), 0, 0.5);

  lb_pgdatabase = gtk_label_new_with_mnemonic ("_Nome Database");
  gtk_widget_set_name (lb_pgdatabase, "lb_pgdatabase");
  gtk_widget_show (lb_pgdatabase);
  gtk_table_attach (GTK_TABLE (table11), lb_pgdatabase, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lb_pgdatabase), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_pgdatabase), 0, 0.5);

  label1227 = gtk_label_new ("Base di dati");
  gtk_widget_set_name (label1227, "label1227");
  gtk_widget_show (label1227);
  gtk_frame_set_label_widget (GTK_FRAME (frame156), label1227);

  dialog_action_area2 = GTK_DIALOG (dlg_config)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (cancelbutton1, "cancelbutton1");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlg_config), cancelbutton1, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  applybutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (applybutton1, "applybutton1");
  gtk_widget_show (applybutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlg_config), applybutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (applybutton1, GTK_CAN_DEFAULT);

  pb_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (pb_close, "pb_close");
  gtk_widget_show (pb_close);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlg_config), pb_close, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (pb_close, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (pb_close, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label642), sb_debug_version);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label289), entry_printer);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label1230), entry_printer);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label1231), entry_printer);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label1232), entry_printer);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label543), entry_data_path);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label827), entry_print_path);
  gtk_label_set_mnemonic_widget (GTK_LABEL (lb_pghost), entry_db_host);
  gtk_label_set_mnemonic_widget (GTK_LABEL (lb_pgport), entry_db_port);
  gtk_label_set_mnemonic_widget (GTK_LABEL (lb_pgdatabase), entry_db_name);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_config, dlg_config, "dlg_config");
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_config, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dlg_config, vbox63, "vbox63");
  GLADE_HOOKUP_OBJECT (dlg_config, frame226, "frame226");
  GLADE_HOOKUP_OBJECT (dlg_config, vbox331, "vbox331");
  GLADE_HOOKUP_OBJECT (dlg_config, table26, "table26");
  GLADE_HOOKUP_OBJECT (dlg_config, label642, "label642");
  GLADE_HOOKUP_OBJECT (dlg_config, sb_debug_version, "sb_debug_version");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_printer, "entry_printer");
  GLADE_HOOKUP_OBJECT (dlg_config, sb_ora_inizio, "sb_ora_inizio");
  GLADE_HOOKUP_OBJECT (dlg_config, sb_ora_fine, "sb_ora_fine");
  GLADE_HOOKUP_OBJECT (dlg_config, sb_numero_operatori, "sb_numero_operatori");
  GLADE_HOOKUP_OBJECT (dlg_config, label289, "label289");
  GLADE_HOOKUP_OBJECT (dlg_config, label1230, "label1230");
  GLADE_HOOKUP_OBJECT (dlg_config, label1231, "label1231");
  GLADE_HOOKUP_OBJECT (dlg_config, label1232, "label1232");
  GLADE_HOOKUP_OBJECT (dlg_config, label1225, "label1225");
  GLADE_HOOKUP_OBJECT (dlg_config, frame164, "frame164");
  GLADE_HOOKUP_OBJECT (dlg_config, table22, "table22");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_data_path, "entry_data_path");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_print_path, "entry_print_path");
  GLADE_HOOKUP_OBJECT (dlg_config, label543, "label543");
  GLADE_HOOKUP_OBJECT (dlg_config, label827, "label827");
  GLADE_HOOKUP_OBJECT (dlg_config, label1226, "label1226");
  GLADE_HOOKUP_OBJECT (dlg_config, frame156, "frame156");
  GLADE_HOOKUP_OBJECT (dlg_config, table11, "table11");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_db_host, "entry_db_host");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_db_port, "entry_db_port");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_db_name, "entry_db_name");
  GLADE_HOOKUP_OBJECT (dlg_config, lb_pghost, "lb_pghost");
  GLADE_HOOKUP_OBJECT (dlg_config, lb_pgport, "lb_pgport");
  GLADE_HOOKUP_OBJECT (dlg_config, lb_pgdatabase, "lb_pgdatabase");
  GLADE_HOOKUP_OBJECT (dlg_config, label1227, "label1227");
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_config, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dlg_config, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dlg_config, applybutton1, "applybutton1");
  GLADE_HOOKUP_OBJECT (dlg_config, pb_close, "pb_close");

  gtk_window_add_accel_group (GTK_WINDOW (dlg_config), accel_group);

  return dlg_config;
}

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *eb_main;
  GtkWidget *vbox375;
  GtkWidget *frame_dati_in_alto;
  GtkWidget *alignment11;
  GtkWidget *hbox189;
  GtkWidget *frame_ordine_collo;
  GtkWidget *alignment12;
  GtkWidget *vbox385;
  GtkWidget *eventbox4;
  GtkWidget *hbox195;
  GtkWidget *lb_ora;
  GtkWidget *lb_titolo_ordine_collo;
  GtkWidget *eventbox5;
  GtkWidget *lb_ordine_collo;
  GtkWidget *vbox384;
  GtkWidget *hbox190;
  GtkWidget *frame543;
  GtkWidget *alignment16;
  GtkWidget *hbox192;
  GtkWidget *eventbox3;
  GtkWidget *lb_titolo_settore;
  GtkWidget *eventbox2;
  GtkWidget *lb_settore;
  GtkWidget *eb_stato_linea;
  GtkWidget *lb_stato_linea;
  GtkWidget *frame546;
  GtkWidget *alignment23;
  GtkWidget *hbox191;
  GtkWidget *eventbox8;
  GtkWidget *lb_titolo_operatore;
  GtkWidget *eventbox7;
  GtkWidget *lb_codice_operatore;
  GtkWidget *eventbox6;
  GtkWidget *lb_dati_operatore;
  GtkWidget *frame540;
  GtkWidget *alignment8;
  GtkWidget *hbox_operazione_copie;
  GtkWidget *frame_operazione;
  GtkWidget *alignment10;
  GtkWidget *hbox193;
  GtkWidget *eb_fronte;
  GtkWidget *img_fronte;
  GtkWidget *eb_operazione;
  GtkWidget *lb_operazione;
  GtkWidget *eb_copie;
  GtkWidget *lb_copie;
  GtkWidget *eb_up;
  GtkWidget *img_up;
  GtkWidget *hbox_variabile;
  GtkWidget *frame_variabile;
  GtkWidget *alignment7;
  GtkWidget *vbox_variabile;
  GtkWidget *hbox194;
  GtkWidget *frame_dati_prodotto;
  GtkWidget *alignment20;
  GtkWidget *table_ubicazione_titolo;
  GtkWidget *eventbox14;
  GtkWidget *lb_codice;
  GtkWidget *eventbox12;
  GtkWidget *lb_ubicazione;
  GtkWidget *eventbox31;
  GtkWidget *lb_titolo;
  GtkWidget *eventbox15;
  GtkWidget *lb_titolo_titolo;
  GtkWidget *eventbox13;
  GtkWidget *lb_titolo_codice;
  GtkWidget *eventbox11;
  GtkWidget *lb_titolo_ubicazione;
  GtkWidget *frame_lettura_barcode_id;
  GtkWidget *vbox386;
  GtkWidget *eb_qt_barcodeid;
  GtkWidget *lb_qt_barcodeid;
  GtkWidget *eb_stato_barcodeid;
  GtkWidget *lb_stato_barcodeid;
  GtkWidget *alignment24;
  GtkWidget *entry_lettura_barcode;
  GtkWidget *frame_statistiche;
  GtkWidget *alignment21;
  GtkWidget *table27;
  GtkWidget *eventbox16;
  GtkWidget *lb_stats_titolo_tabella;
  GtkWidget *eventbox17;
  GtkWidget *lb_stats_titolo_ordini;
  GtkWidget *eventbox18;
  GtkWidget *lb_stats_titolo_colli;
  GtkWidget *eventbox19;
  GtkWidget *lb_stats_titolo_righe;
  GtkWidget *eventbox20;
  GtkWidget *lb_stats_titolo_copie;
  GtkWidget *eventbox21;
  GtkWidget *lb_stats_titolo_da_prelevare;
  GtkWidget *eventbox22;
  GtkWidget *lb_stats_ordini_da_prelevare;
  GtkWidget *eventbox23;
  GtkWidget *lb_stats_colli_da_prelevare;
  GtkWidget *eventbox24;
  GtkWidget *lb_stats_righe_da_prelevare;
  GtkWidget *eventbox25;
  GtkWidget *lb_stats_copie_da_prelevare;
  GtkWidget *eventbox26;
  GtkWidget *lb_stats_titolo_prelevati;
  GtkWidget *eventbox27;
  GtkWidget *lb_stats_ordini_prelevati;
  GtkWidget *eventbox28;
  GtkWidget *lb_stats_colli_prelevati;
  GtkWidget *eventbox29;
  GtkWidget *lb_stats_righe_prelevati;
  GtkWidget *eventbox30;
  GtkWidget *lb_stats_copie_prelevati;
  GtkWidget *frame_lista_colli;
  GtkWidget *sw_lista_colli;

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main_window, "main_window");
  gtk_widget_set_size_request (main_window, 1366, 768);
  gtk_window_set_title (GTK_WINDOW (main_window), "display");
  gtk_window_set_position (GTK_WINDOW (main_window), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_decorated (GTK_WINDOW (main_window), FALSE);

  eb_main = gtk_event_box_new ();
  gtk_widget_set_name (eb_main, "eb_main");
  gtk_widget_show (eb_main);
  gtk_container_add (GTK_CONTAINER (main_window), eb_main);

  vbox375 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox375, "vbox375");
  gtk_widget_show (vbox375);
  gtk_container_add (GTK_CONTAINER (eb_main), vbox375);

  frame_dati_in_alto = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_dati_in_alto, "frame_dati_in_alto");
  gtk_widget_show (frame_dati_in_alto);
  gtk_box_pack_start (GTK_BOX (vbox375), frame_dati_in_alto, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_dati_in_alto), GTK_SHADOW_NONE);

  alignment11 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment11, "alignment11");
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (frame_dati_in_alto), alignment11);

  hbox189 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox189, "hbox189");
  gtk_widget_show (hbox189);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox189);

  frame_ordine_collo = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_ordine_collo, "frame_ordine_collo");
  gtk_widget_show (frame_ordine_collo);
  gtk_box_pack_start (GTK_BOX (hbox189), frame_ordine_collo, FALSE, TRUE, 0);
  gtk_widget_set_size_request (frame_ordine_collo, 900, -1);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_ordine_collo), GTK_SHADOW_NONE);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment12, "alignment12");
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (frame_ordine_collo), alignment12);

  vbox385 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox385, "vbox385");
  gtk_widget_show (vbox385);
  gtk_container_add (GTK_CONTAINER (alignment12), vbox385);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox4, "eventbox4");
  gtk_widget_show (eventbox4);
  gtk_box_pack_start (GTK_BOX (vbox385), eventbox4, TRUE, TRUE, 0);

  hbox195 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox195, "hbox195");
  gtk_widget_show (hbox195);
  gtk_container_add (GTK_CONTAINER (eventbox4), hbox195);

  lb_ora = gtk_label_new ("");
  gtk_widget_set_name (lb_ora, "lb_ora");
  gtk_widget_show (lb_ora);
  gtk_box_pack_start (GTK_BOX (hbox195), lb_ora, TRUE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (lb_ora), TRUE);
  gtk_misc_set_padding (GTK_MISC (lb_ora), 5, 1);

  lb_titolo_ordine_collo = gtk_label_new ("");
  gtk_widget_set_name (lb_titolo_ordine_collo, "lb_titolo_ordine_collo");
  gtk_widget_show (lb_titolo_ordine_collo);
  gtk_box_pack_start (GTK_BOX (hbox195), lb_titolo_ordine_collo, TRUE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (lb_titolo_ordine_collo), TRUE);
  gtk_misc_set_padding (GTK_MISC (lb_titolo_ordine_collo), 5, 1);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox5, "eventbox5");
  gtk_widget_show (eventbox5);
  gtk_box_pack_start (GTK_BOX (vbox385), eventbox5, TRUE, TRUE, 0);

  lb_ordine_collo = gtk_label_new ("");
  gtk_widget_set_name (lb_ordine_collo, "lb_ordine_collo");
  gtk_widget_show (lb_ordine_collo);
  gtk_container_add (GTK_CONTAINER (eventbox5), lb_ordine_collo);
  gtk_label_set_use_markup (GTK_LABEL (lb_ordine_collo), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_ordine_collo), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (lb_ordine_collo), 5, 1);

  vbox384 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox384, "vbox384");
  gtk_widget_show (vbox384);
  gtk_box_pack_start (GTK_BOX (hbox189), vbox384, TRUE, TRUE, 0);

  hbox190 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox190, "hbox190");
  gtk_widget_show (hbox190);
  gtk_box_pack_start (GTK_BOX (vbox384), hbox190, TRUE, TRUE, 0);

  frame543 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame543, "frame543");
  gtk_widget_show (frame543);
  gtk_box_pack_start (GTK_BOX (hbox190), frame543, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame543), GTK_SHADOW_NONE);

  alignment16 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment16, "alignment16");
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (frame543), alignment16);

  hbox192 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox192, "hbox192");
  gtk_widget_show (hbox192);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox192);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox3, "eventbox3");
  gtk_widget_show (eventbox3);
  gtk_box_pack_start (GTK_BOX (hbox192), eventbox3, FALSE, TRUE, 0);

  lb_titolo_settore = gtk_label_new ("SETTORE");
  gtk_widget_set_name (lb_titolo_settore, "lb_titolo_settore");
  gtk_widget_show (lb_titolo_settore);
  gtk_container_add (GTK_CONTAINER (eventbox3), lb_titolo_settore);
  gtk_label_set_use_markup (GTK_LABEL (lb_titolo_settore), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_titolo_settore), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_titolo_settore), 5, 1);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox2, "eventbox2");
  gtk_widget_show (eventbox2);
  gtk_box_pack_start (GTK_BOX (hbox192), eventbox2, TRUE, TRUE, 0);

  lb_settore = gtk_label_new ("01");
  gtk_widget_set_name (lb_settore, "lb_settore");
  gtk_widget_show (lb_settore);
  gtk_container_add (GTK_CONTAINER (eventbox2), lb_settore);
  gtk_label_set_use_markup (GTK_LABEL (lb_settore), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_settore), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_settore), 5, 1);

  eb_stato_linea = gtk_event_box_new ();
  gtk_widget_set_name (eb_stato_linea, "eb_stato_linea");
  gtk_widget_show (eb_stato_linea);
  gtk_box_pack_start (GTK_BOX (hbox192), eb_stato_linea, TRUE, TRUE, 0);

  lb_stato_linea = gtk_label_new ("START");
  gtk_widget_set_name (lb_stato_linea, "lb_stato_linea");
  gtk_widget_show (lb_stato_linea);
  gtk_container_add (GTK_CONTAINER (eb_stato_linea), lb_stato_linea);
  gtk_label_set_use_markup (GTK_LABEL (lb_stato_linea), TRUE);
  gtk_misc_set_padding (GTK_MISC (lb_stato_linea), 5, 1);

  frame546 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame546, "frame546");
  gtk_widget_show (frame546);
  gtk_box_pack_start (GTK_BOX (vbox384), frame546, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame546), GTK_SHADOW_NONE);

  alignment23 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment23, "alignment23");
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (frame546), alignment23);

  hbox191 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox191, "hbox191");
  gtk_widget_show (hbox191);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox191);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox8, "eventbox8");
  gtk_widget_show (eventbox8);
  gtk_box_pack_start (GTK_BOX (hbox191), eventbox8, FALSE, TRUE, 0);

  lb_titolo_operatore = gtk_label_new ("OPERATORE");
  gtk_widget_set_name (lb_titolo_operatore, "lb_titolo_operatore");
  gtk_widget_show (lb_titolo_operatore);
  gtk_container_add (GTK_CONTAINER (eventbox8), lb_titolo_operatore);
  gtk_label_set_use_markup (GTK_LABEL (lb_titolo_operatore), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_titolo_operatore), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_titolo_operatore), 5, 1);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox7, "eventbox7");
  gtk_widget_show (eventbox7);
  gtk_box_pack_start (GTK_BOX (hbox191), eventbox7, TRUE, TRUE, 0);

  lb_codice_operatore = gtk_label_new ("01");
  gtk_widget_set_name (lb_codice_operatore, "lb_codice_operatore");
  gtk_widget_show (lb_codice_operatore);
  gtk_container_add (GTK_CONTAINER (eventbox7), lb_codice_operatore);
  gtk_label_set_use_markup (GTK_LABEL (lb_codice_operatore), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_codice_operatore), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_codice_operatore), 5, 1);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox6, "eventbox6");
  gtk_widget_show (eventbox6);
  gtk_box_pack_start (GTK_BOX (hbox191), eventbox6, TRUE, TRUE, 0);

  lb_dati_operatore = gtk_label_new ("OPERATORE");
  gtk_widget_set_name (lb_dati_operatore, "lb_dati_operatore");
  gtk_widget_show (lb_dati_operatore);
  gtk_container_add (GTK_CONTAINER (eventbox6), lb_dati_operatore);
  gtk_label_set_use_markup (GTK_LABEL (lb_dati_operatore), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_dati_operatore), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_dati_operatore), 5, 1);

  frame540 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame540, "frame540");
  gtk_widget_show (frame540);
  gtk_box_pack_start (GTK_BOX (vbox375), frame540, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame540), GTK_SHADOW_NONE);

  alignment8 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment8, "alignment8");
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (frame540), alignment8);

  hbox_operazione_copie = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox_operazione_copie, "hbox_operazione_copie");
  gtk_widget_show (hbox_operazione_copie);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox_operazione_copie);

  frame_operazione = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_operazione, "frame_operazione");
  gtk_widget_show (frame_operazione);
  gtk_box_pack_start (GTK_BOX (hbox_operazione_copie), frame_operazione, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_operazione), GTK_SHADOW_NONE);

  alignment10 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment10, "alignment10");
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (frame_operazione), alignment10);

  hbox193 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox193, "hbox193");
  gtk_widget_show (hbox193);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox193);

  eb_fronte = gtk_event_box_new ();
  gtk_widget_set_name (eb_fronte, "eb_fronte");
  gtk_widget_show (eb_fronte);
  gtk_box_pack_start (GTK_BOX (hbox193), eb_fronte, TRUE, TRUE, 0);
  gtk_widget_set_size_request (eb_fronte, 200, 200);

  img_fronte = create_pixmap (main_window, NULL);
  gtk_widget_set_name (img_fronte, "img_fronte");
  gtk_widget_show (img_fronte);
  gtk_container_add (GTK_CONTAINER (eb_fronte), img_fronte);

  eb_operazione = gtk_event_box_new ();
  gtk_widget_set_name (eb_operazione, "eb_operazione");
  gtk_widget_show (eb_operazione);
  gtk_box_pack_start (GTK_BOX (hbox193), eb_operazione, TRUE, TRUE, 0);

  lb_operazione = gtk_label_new ("OPERAZIONE");
  gtk_widget_set_name (lb_operazione, "lb_operazione");
  gtk_widget_show (lb_operazione);
  gtk_container_add (GTK_CONTAINER (eb_operazione), lb_operazione);
  gtk_label_set_use_markup (GTK_LABEL (lb_operazione), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_operazione), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (lb_operazione), 5, 1);

  eb_copie = gtk_event_box_new ();
  gtk_widget_set_name (eb_copie, "eb_copie");
  gtk_widget_show (eb_copie);
  gtk_box_pack_start (GTK_BOX (hbox193), eb_copie, TRUE, TRUE, 0);

  lb_copie = gtk_label_new ("COPIE");
  gtk_widget_set_name (lb_copie, "lb_copie");
  gtk_widget_show (lb_copie);
  gtk_container_add (GTK_CONTAINER (eb_copie), lb_copie);
  gtk_label_set_use_markup (GTK_LABEL (lb_copie), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_copie), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lb_copie), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_copie), 5, 1);

  eb_up = gtk_event_box_new ();
  gtk_widget_set_name (eb_up, "eb_up");
  gtk_widget_show (eb_up);
  gtk_box_pack_start (GTK_BOX (hbox193), eb_up, TRUE, TRUE, 0);
  gtk_widget_set_size_request (eb_up, 200, 200);

  img_up = create_pixmap (main_window, NULL);
  gtk_widget_set_name (img_up, "img_up");
  gtk_widget_show (img_up);
  gtk_container_add (GTK_CONTAINER (eb_up), img_up);

  hbox_variabile = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox_variabile, "hbox_variabile");
  gtk_widget_show (hbox_variabile);
  gtk_box_pack_start (GTK_BOX (vbox375), hbox_variabile, TRUE, TRUE, 0);

  frame_variabile = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_variabile, "frame_variabile");
  gtk_widget_show (frame_variabile);
  gtk_box_pack_start (GTK_BOX (hbox_variabile), frame_variabile, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_variabile), GTK_SHADOW_NONE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment7, "alignment7");
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (frame_variabile), alignment7);

  vbox_variabile = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox_variabile, "vbox_variabile");
  gtk_widget_show (vbox_variabile);
  gtk_container_add (GTK_CONTAINER (alignment7), vbox_variabile);

  hbox194 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox194, "hbox194");
  gtk_widget_show (hbox194);
  gtk_box_pack_start (GTK_BOX (vbox_variabile), hbox194, TRUE, TRUE, 0);

  frame_dati_prodotto = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_dati_prodotto, "frame_dati_prodotto");
  gtk_widget_show (frame_dati_prodotto);
  gtk_box_pack_start (GTK_BOX (hbox194), frame_dati_prodotto, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_dati_prodotto), GTK_SHADOW_NONE);

  alignment20 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment20, "alignment20");
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (frame_dati_prodotto), alignment20);

  table_ubicazione_titolo = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table_ubicazione_titolo, "table_ubicazione_titolo");
  gtk_widget_show (table_ubicazione_titolo);
  gtk_container_add (GTK_CONTAINER (alignment20), table_ubicazione_titolo);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox14, "eventbox14");
  gtk_widget_show (eventbox14);
  gtk_table_attach (GTK_TABLE (table_ubicazione_titolo), eventbox14, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_codice = gtk_label_new ("");
  gtk_widget_set_name (lb_codice, "lb_codice");
  gtk_widget_show (lb_codice);
  gtk_container_add (GTK_CONTAINER (eventbox14), lb_codice);
  gtk_label_set_use_markup (GTK_LABEL (lb_codice), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_codice), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_codice), 5, 1);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox12, "eventbox12");
  gtk_widget_show (eventbox12);
  gtk_table_attach (GTK_TABLE (table_ubicazione_titolo), eventbox12, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_ubicazione = gtk_label_new ("");
  gtk_widget_set_name (lb_ubicazione, "lb_ubicazione");
  gtk_widget_show (lb_ubicazione);
  gtk_container_add (GTK_CONTAINER (eventbox12), lb_ubicazione);
  gtk_label_set_use_markup (GTK_LABEL (lb_ubicazione), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_ubicazione), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_ubicazione), 5, 1);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox31, "eventbox31");
  gtk_widget_show (eventbox31);
  gtk_table_attach (GTK_TABLE (table_ubicazione_titolo), eventbox31, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL), 0, 0);

  lb_titolo = gtk_label_new ("");
  gtk_widget_set_name (lb_titolo, "lb_titolo");
  gtk_widget_show (lb_titolo);
  gtk_container_add (GTK_CONTAINER (eventbox31), lb_titolo);
  gtk_label_set_use_markup (GTK_LABEL (lb_titolo), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_titolo), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_titolo), 2, 1);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox15, "eventbox15");
  gtk_widget_show (eventbox15);
  gtk_table_attach (GTK_TABLE (table_ubicazione_titolo), eventbox15, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_titolo_titolo = gtk_label_new ("");
  gtk_widget_set_name (lb_titolo_titolo, "lb_titolo_titolo");
  gtk_widget_show (lb_titolo_titolo);
  gtk_container_add (GTK_CONTAINER (eventbox15), lb_titolo_titolo);
  gtk_label_set_use_markup (GTK_LABEL (lb_titolo_titolo), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_titolo_titolo), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_titolo_titolo), 2, 1);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox13, "eventbox13");
  gtk_widget_show (eventbox13);
  gtk_table_attach (GTK_TABLE (table_ubicazione_titolo), eventbox13, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_titolo_codice = gtk_label_new ("");
  gtk_widget_set_name (lb_titolo_codice, "lb_titolo_codice");
  gtk_widget_show (lb_titolo_codice);
  gtk_container_add (GTK_CONTAINER (eventbox13), lb_titolo_codice);
  gtk_label_set_use_markup (GTK_LABEL (lb_titolo_codice), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_titolo_codice), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_titolo_codice), 5, 1);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox11, "eventbox11");
  gtk_widget_show (eventbox11);
  gtk_table_attach (GTK_TABLE (table_ubicazione_titolo), eventbox11, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_titolo_ubicazione = gtk_label_new ("");
  gtk_widget_set_name (lb_titolo_ubicazione, "lb_titolo_ubicazione");
  gtk_widget_show (lb_titolo_ubicazione);
  gtk_container_add (GTK_CONTAINER (eventbox11), lb_titolo_ubicazione);
  gtk_label_set_use_markup (GTK_LABEL (lb_titolo_ubicazione), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_titolo_ubicazione), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_titolo_ubicazione), 5, 1);

  frame_lettura_barcode_id = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_lettura_barcode_id, "frame_lettura_barcode_id");
  gtk_widget_show (frame_lettura_barcode_id);
  gtk_box_pack_start (GTK_BOX (hbox194), frame_lettura_barcode_id, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_lettura_barcode_id), GTK_SHADOW_NONE);

  vbox386 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox386, "vbox386");
  gtk_widget_show (vbox386);
  gtk_container_add (GTK_CONTAINER (frame_lettura_barcode_id), vbox386);

  eb_qt_barcodeid = gtk_event_box_new ();
  gtk_widget_set_name (eb_qt_barcodeid, "eb_qt_barcodeid");
  gtk_widget_show (eb_qt_barcodeid);
  gtk_box_pack_start (GTK_BOX (vbox386), eb_qt_barcodeid, TRUE, TRUE, 0);

  lb_qt_barcodeid = gtk_label_new ("COPIE");
  gtk_widget_set_name (lb_qt_barcodeid, "lb_qt_barcodeid");
  gtk_widget_show (lb_qt_barcodeid);
  gtk_container_add (GTK_CONTAINER (eb_qt_barcodeid), lb_qt_barcodeid);
  gtk_label_set_use_markup (GTK_LABEL (lb_qt_barcodeid), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_qt_barcodeid), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (lb_qt_barcodeid), 5, 1);

  eb_stato_barcodeid = gtk_event_box_new ();
  gtk_widget_set_name (eb_stato_barcodeid, "eb_stato_barcodeid");
  gtk_widget_show (eb_stato_barcodeid);
  gtk_box_pack_start (GTK_BOX (vbox386), eb_stato_barcodeid, TRUE, TRUE, 0);

  lb_stato_barcodeid = gtk_label_new ("OPERAZIONE");
  gtk_widget_set_name (lb_stato_barcodeid, "lb_stato_barcodeid");
  gtk_widget_show (lb_stato_barcodeid);
  gtk_container_add (GTK_CONTAINER (eb_stato_barcodeid), lb_stato_barcodeid);
  gtk_label_set_use_markup (GTK_LABEL (lb_stato_barcodeid), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_stato_barcodeid), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (lb_stato_barcodeid), 5, 1);

  alignment24 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment24, "alignment24");
  gtk_widget_show (alignment24);
  gtk_box_pack_start (GTK_BOX (vbox386), alignment24, FALSE, FALSE, 0);

  entry_lettura_barcode = gtk_entry_new ();
  gtk_widget_set_name (entry_lettura_barcode, "entry_lettura_barcode");
  gtk_widget_show (entry_lettura_barcode);
  gtk_container_add (GTK_CONTAINER (alignment24), entry_lettura_barcode);
  GTK_WIDGET_SET_FLAGS (entry_lettura_barcode, GTK_CAN_DEFAULT);
  gtk_entry_set_max_length (GTK_ENTRY (entry_lettura_barcode), 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_lettura_barcode), 8226);

  frame_statistiche = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_statistiche, "frame_statistiche");
  gtk_widget_show (frame_statistiche);
  gtk_box_pack_start (GTK_BOX (vbox_variabile), frame_statistiche, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_statistiche), GTK_SHADOW_NONE);

  alignment21 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment21, "alignment21");
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (frame_statistiche), alignment21);

  table27 = gtk_table_new (3, 5, FALSE);
  gtk_widget_set_name (table27, "table27");
  gtk_widget_show (table27);
  gtk_container_add (GTK_CONTAINER (alignment21), table27);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox16, "eventbox16");
  gtk_widget_show (eventbox16);
  gtk_table_attach (GTK_TABLE (table27), eventbox16, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  lb_stats_titolo_tabella = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_titolo_tabella, "lb_stats_titolo_tabella");
  gtk_widget_show (lb_stats_titolo_tabella);
  gtk_container_add (GTK_CONTAINER (eventbox16), lb_stats_titolo_tabella);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_titolo_tabella), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_titolo_tabella), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_titolo_tabella), 5, 1);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox17, "eventbox17");
  gtk_widget_show (eventbox17);
  gtk_table_attach (GTK_TABLE (table27), eventbox17, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_titolo_ordini = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_titolo_ordini, "lb_stats_titolo_ordini");
  gtk_widget_show (lb_stats_titolo_ordini);
  gtk_container_add (GTK_CONTAINER (eventbox17), lb_stats_titolo_ordini);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_titolo_ordini), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_titolo_ordini), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_titolo_ordini), 5, 1);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox18, "eventbox18");
  gtk_widget_show (eventbox18);
  gtk_table_attach (GTK_TABLE (table27), eventbox18, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_titolo_colli = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_titolo_colli, "lb_stats_titolo_colli");
  gtk_widget_show (lb_stats_titolo_colli);
  gtk_container_add (GTK_CONTAINER (eventbox18), lb_stats_titolo_colli);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_titolo_colli), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_titolo_colli), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_titolo_colli), 5, 1);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox19, "eventbox19");
  gtk_widget_show (eventbox19);
  gtk_table_attach (GTK_TABLE (table27), eventbox19, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_titolo_righe = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_titolo_righe, "lb_stats_titolo_righe");
  gtk_widget_show (lb_stats_titolo_righe);
  gtk_container_add (GTK_CONTAINER (eventbox19), lb_stats_titolo_righe);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_titolo_righe), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_titolo_righe), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_titolo_righe), 5, 1);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox20, "eventbox20");
  gtk_widget_show (eventbox20);
  gtk_table_attach (GTK_TABLE (table27), eventbox20, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_titolo_copie = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_titolo_copie, "lb_stats_titolo_copie");
  gtk_widget_show (lb_stats_titolo_copie);
  gtk_container_add (GTK_CONTAINER (eventbox20), lb_stats_titolo_copie);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_titolo_copie), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_titolo_copie), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_titolo_copie), 5, 1);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox21, "eventbox21");
  gtk_widget_show (eventbox21);
  gtk_table_attach (GTK_TABLE (table27), eventbox21, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  lb_stats_titolo_da_prelevare = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_titolo_da_prelevare, "lb_stats_titolo_da_prelevare");
  gtk_widget_show (lb_stats_titolo_da_prelevare);
  gtk_container_add (GTK_CONTAINER (eventbox21), lb_stats_titolo_da_prelevare);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_titolo_da_prelevare), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_titolo_da_prelevare), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_titolo_da_prelevare), 5, 1);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox22, "eventbox22");
  gtk_widget_show (eventbox22);
  gtk_table_attach (GTK_TABLE (table27), eventbox22, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_ordini_da_prelevare = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_ordini_da_prelevare, "lb_stats_ordini_da_prelevare");
  gtk_widget_show (lb_stats_ordini_da_prelevare);
  gtk_container_add (GTK_CONTAINER (eventbox22), lb_stats_ordini_da_prelevare);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_ordini_da_prelevare), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_ordini_da_prelevare), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_ordini_da_prelevare), 5, 1);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox23, "eventbox23");
  gtk_widget_show (eventbox23);
  gtk_table_attach (GTK_TABLE (table27), eventbox23, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_colli_da_prelevare = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_colli_da_prelevare, "lb_stats_colli_da_prelevare");
  gtk_widget_show (lb_stats_colli_da_prelevare);
  gtk_container_add (GTK_CONTAINER (eventbox23), lb_stats_colli_da_prelevare);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_colli_da_prelevare), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_colli_da_prelevare), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_colli_da_prelevare), 5, 1);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox24, "eventbox24");
  gtk_widget_show (eventbox24);
  gtk_table_attach (GTK_TABLE (table27), eventbox24, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_righe_da_prelevare = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_righe_da_prelevare, "lb_stats_righe_da_prelevare");
  gtk_widget_show (lb_stats_righe_da_prelevare);
  gtk_container_add (GTK_CONTAINER (eventbox24), lb_stats_righe_da_prelevare);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_righe_da_prelevare), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_righe_da_prelevare), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_righe_da_prelevare), 5, 1);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox25, "eventbox25");
  gtk_widget_show (eventbox25);
  gtk_table_attach (GTK_TABLE (table27), eventbox25, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_copie_da_prelevare = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_copie_da_prelevare, "lb_stats_copie_da_prelevare");
  gtk_widget_show (lb_stats_copie_da_prelevare);
  gtk_container_add (GTK_CONTAINER (eventbox25), lb_stats_copie_da_prelevare);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_copie_da_prelevare), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_copie_da_prelevare), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_copie_da_prelevare), 5, 1);

  eventbox26 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox26, "eventbox26");
  gtk_widget_show (eventbox26);
  gtk_table_attach (GTK_TABLE (table27), eventbox26, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  lb_stats_titolo_prelevati = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_titolo_prelevati, "lb_stats_titolo_prelevati");
  gtk_widget_show (lb_stats_titolo_prelevati);
  gtk_container_add (GTK_CONTAINER (eventbox26), lb_stats_titolo_prelevati);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_titolo_prelevati), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_titolo_prelevati), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_titolo_prelevati), 5, 1);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox27, "eventbox27");
  gtk_widget_show (eventbox27);
  gtk_table_attach (GTK_TABLE (table27), eventbox27, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_ordini_prelevati = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_ordini_prelevati, "lb_stats_ordini_prelevati");
  gtk_widget_show (lb_stats_ordini_prelevati);
  gtk_container_add (GTK_CONTAINER (eventbox27), lb_stats_ordini_prelevati);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_ordini_prelevati), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_ordini_prelevati), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_ordini_prelevati), 5, 1);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox28, "eventbox28");
  gtk_widget_show (eventbox28);
  gtk_table_attach (GTK_TABLE (table27), eventbox28, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_colli_prelevati = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_colli_prelevati, "lb_stats_colli_prelevati");
  gtk_widget_show (lb_stats_colli_prelevati);
  gtk_container_add (GTK_CONTAINER (eventbox28), lb_stats_colli_prelevati);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_colli_prelevati), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_colli_prelevati), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_colli_prelevati), 5, 1);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox29, "eventbox29");
  gtk_widget_show (eventbox29);
  gtk_table_attach (GTK_TABLE (table27), eventbox29, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_righe_prelevati = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_righe_prelevati, "lb_stats_righe_prelevati");
  gtk_widget_show (lb_stats_righe_prelevati);
  gtk_container_add (GTK_CONTAINER (eventbox29), lb_stats_righe_prelevati);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_righe_prelevati), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_righe_prelevati), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_righe_prelevati), 5, 1);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox30, "eventbox30");
  gtk_widget_show (eventbox30);
  gtk_table_attach (GTK_TABLE (table27), eventbox30, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_stats_copie_prelevati = gtk_label_new ("");
  gtk_widget_set_name (lb_stats_copie_prelevati, "lb_stats_copie_prelevati");
  gtk_widget_show (lb_stats_copie_prelevati);
  gtk_container_add (GTK_CONTAINER (eventbox30), lb_stats_copie_prelevati);
  gtk_label_set_use_markup (GTK_LABEL (lb_stats_copie_prelevati), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_stats_copie_prelevati), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_stats_copie_prelevati), 5, 1);

  frame_lista_colli = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_lista_colli, "frame_lista_colli");
  gtk_widget_show (frame_lista_colli);
  gtk_box_pack_start (GTK_BOX (vbox_variabile), frame_lista_colli, TRUE, TRUE, 0);
  gtk_widget_set_size_request (frame_lista_colli, -1, 250);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_lista_colli), GTK_SHADOW_NONE);

  sw_lista_colli = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (sw_lista_colli, "sw_lista_colli");
  gtk_widget_show (sw_lista_colli);
  gtk_container_add (GTK_CONTAINER (frame_lista_colli), sw_lista_colli);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (sw_lista_colli), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  g_signal_connect ((gpointer) main_window, "delete_event",
                    G_CALLBACK (do_exit),
                    NULL);
  g_signal_connect ((gpointer) main_window, "destroy_event",
                    G_CALLBACK (do_exit),
                    NULL);
  g_signal_connect ((gpointer) entry_lettura_barcode, "activate",
                    G_CALLBACK (on_entry_lettura_barcode_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, eb_main, "eb_main");
  GLADE_HOOKUP_OBJECT (main_window, vbox375, "vbox375");
  GLADE_HOOKUP_OBJECT (main_window, frame_dati_in_alto, "frame_dati_in_alto");
  GLADE_HOOKUP_OBJECT (main_window, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (main_window, hbox189, "hbox189");
  GLADE_HOOKUP_OBJECT (main_window, frame_ordine_collo, "frame_ordine_collo");
  GLADE_HOOKUP_OBJECT (main_window, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (main_window, vbox385, "vbox385");
  GLADE_HOOKUP_OBJECT (main_window, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (main_window, hbox195, "hbox195");
  GLADE_HOOKUP_OBJECT (main_window, lb_ora, "lb_ora");
  GLADE_HOOKUP_OBJECT (main_window, lb_titolo_ordine_collo, "lb_titolo_ordine_collo");
  GLADE_HOOKUP_OBJECT (main_window, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (main_window, lb_ordine_collo, "lb_ordine_collo");
  GLADE_HOOKUP_OBJECT (main_window, vbox384, "vbox384");
  GLADE_HOOKUP_OBJECT (main_window, hbox190, "hbox190");
  GLADE_HOOKUP_OBJECT (main_window, frame543, "frame543");
  GLADE_HOOKUP_OBJECT (main_window, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (main_window, hbox192, "hbox192");
  GLADE_HOOKUP_OBJECT (main_window, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (main_window, lb_titolo_settore, "lb_titolo_settore");
  GLADE_HOOKUP_OBJECT (main_window, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (main_window, lb_settore, "lb_settore");
  GLADE_HOOKUP_OBJECT (main_window, eb_stato_linea, "eb_stato_linea");
  GLADE_HOOKUP_OBJECT (main_window, lb_stato_linea, "lb_stato_linea");
  GLADE_HOOKUP_OBJECT (main_window, frame546, "frame546");
  GLADE_HOOKUP_OBJECT (main_window, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (main_window, hbox191, "hbox191");
  GLADE_HOOKUP_OBJECT (main_window, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (main_window, lb_titolo_operatore, "lb_titolo_operatore");
  GLADE_HOOKUP_OBJECT (main_window, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (main_window, lb_codice_operatore, "lb_codice_operatore");
  GLADE_HOOKUP_OBJECT (main_window, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (main_window, lb_dati_operatore, "lb_dati_operatore");
  GLADE_HOOKUP_OBJECT (main_window, frame540, "frame540");
  GLADE_HOOKUP_OBJECT (main_window, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (main_window, hbox_operazione_copie, "hbox_operazione_copie");
  GLADE_HOOKUP_OBJECT (main_window, frame_operazione, "frame_operazione");
  GLADE_HOOKUP_OBJECT (main_window, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (main_window, hbox193, "hbox193");
  GLADE_HOOKUP_OBJECT (main_window, eb_fronte, "eb_fronte");
  GLADE_HOOKUP_OBJECT (main_window, img_fronte, "img_fronte");
  GLADE_HOOKUP_OBJECT (main_window, eb_operazione, "eb_operazione");
  GLADE_HOOKUP_OBJECT (main_window, lb_operazione, "lb_operazione");
  GLADE_HOOKUP_OBJECT (main_window, eb_copie, "eb_copie");
  GLADE_HOOKUP_OBJECT (main_window, lb_copie, "lb_copie");
  GLADE_HOOKUP_OBJECT (main_window, eb_up, "eb_up");
  GLADE_HOOKUP_OBJECT (main_window, img_up, "img_up");
  GLADE_HOOKUP_OBJECT (main_window, hbox_variabile, "hbox_variabile");
  GLADE_HOOKUP_OBJECT (main_window, frame_variabile, "frame_variabile");
  GLADE_HOOKUP_OBJECT (main_window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (main_window, vbox_variabile, "vbox_variabile");
  GLADE_HOOKUP_OBJECT (main_window, hbox194, "hbox194");
  GLADE_HOOKUP_OBJECT (main_window, frame_dati_prodotto, "frame_dati_prodotto");
  GLADE_HOOKUP_OBJECT (main_window, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (main_window, table_ubicazione_titolo, "table_ubicazione_titolo");
  GLADE_HOOKUP_OBJECT (main_window, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (main_window, lb_codice, "lb_codice");
  GLADE_HOOKUP_OBJECT (main_window, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (main_window, lb_ubicazione, "lb_ubicazione");
  GLADE_HOOKUP_OBJECT (main_window, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (main_window, lb_titolo, "lb_titolo");
  GLADE_HOOKUP_OBJECT (main_window, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (main_window, lb_titolo_titolo, "lb_titolo_titolo");
  GLADE_HOOKUP_OBJECT (main_window, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (main_window, lb_titolo_codice, "lb_titolo_codice");
  GLADE_HOOKUP_OBJECT (main_window, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (main_window, lb_titolo_ubicazione, "lb_titolo_ubicazione");
  GLADE_HOOKUP_OBJECT (main_window, frame_lettura_barcode_id, "frame_lettura_barcode_id");
  GLADE_HOOKUP_OBJECT (main_window, vbox386, "vbox386");
  GLADE_HOOKUP_OBJECT (main_window, eb_qt_barcodeid, "eb_qt_barcodeid");
  GLADE_HOOKUP_OBJECT (main_window, lb_qt_barcodeid, "lb_qt_barcodeid");
  GLADE_HOOKUP_OBJECT (main_window, eb_stato_barcodeid, "eb_stato_barcodeid");
  GLADE_HOOKUP_OBJECT (main_window, lb_stato_barcodeid, "lb_stato_barcodeid");
  GLADE_HOOKUP_OBJECT (main_window, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (main_window, entry_lettura_barcode, "entry_lettura_barcode");
  GLADE_HOOKUP_OBJECT (main_window, frame_statistiche, "frame_statistiche");
  GLADE_HOOKUP_OBJECT (main_window, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (main_window, table27, "table27");
  GLADE_HOOKUP_OBJECT (main_window, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_titolo_tabella, "lb_stats_titolo_tabella");
  GLADE_HOOKUP_OBJECT (main_window, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_titolo_ordini, "lb_stats_titolo_ordini");
  GLADE_HOOKUP_OBJECT (main_window, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_titolo_colli, "lb_stats_titolo_colli");
  GLADE_HOOKUP_OBJECT (main_window, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_titolo_righe, "lb_stats_titolo_righe");
  GLADE_HOOKUP_OBJECT (main_window, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_titolo_copie, "lb_stats_titolo_copie");
  GLADE_HOOKUP_OBJECT (main_window, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_titolo_da_prelevare, "lb_stats_titolo_da_prelevare");
  GLADE_HOOKUP_OBJECT (main_window, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_ordini_da_prelevare, "lb_stats_ordini_da_prelevare");
  GLADE_HOOKUP_OBJECT (main_window, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_colli_da_prelevare, "lb_stats_colli_da_prelevare");
  GLADE_HOOKUP_OBJECT (main_window, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_righe_da_prelevare, "lb_stats_righe_da_prelevare");
  GLADE_HOOKUP_OBJECT (main_window, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_copie_da_prelevare, "lb_stats_copie_da_prelevare");
  GLADE_HOOKUP_OBJECT (main_window, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_titolo_prelevati, "lb_stats_titolo_prelevati");
  GLADE_HOOKUP_OBJECT (main_window, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_ordini_prelevati, "lb_stats_ordini_prelevati");
  GLADE_HOOKUP_OBJECT (main_window, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_colli_prelevati, "lb_stats_colli_prelevati");
  GLADE_HOOKUP_OBJECT (main_window, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_righe_prelevati, "lb_stats_righe_prelevati");
  GLADE_HOOKUP_OBJECT (main_window, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (main_window, lb_stats_copie_prelevati, "lb_stats_copie_prelevati");
  GLADE_HOOKUP_OBJECT (main_window, frame_lista_colli, "frame_lista_colli");
  GLADE_HOOKUP_OBJECT (main_window, sw_lista_colli, "sw_lista_colli");

  gtk_widget_grab_focus (entry_lettura_barcode);
  gtk_widget_grab_default (entry_lettura_barcode);
  return main_window;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vp_lista_colli;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window1, "window1");
  gtk_window_set_title (GTK_WINDOW (window1), "window1");

  vp_lista_colli = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (vp_lista_colli, "vp_lista_colli");
  gtk_widget_show (vp_lista_colli);
  gtk_container_add (GTK_CONTAINER (window1), vp_lista_colli);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (vp_lista_colli), GTK_SHADOW_NONE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vp_lista_colli, "vp_lista_colli");

  return window1;
}

