#!/bin/bash

# st - Thu Jan 10 10:43:43 CET 2002
# applet di spegnimento macchina database

zenity --title "TEST SETTORI" --width=560 --height=760 --list --text "Test Settori" --column "ISOLA" --column "SETTORE" 1 1 1 2 1 3 1 4 1 5 1 6 1 7 1 8 2 1 2 2 2 3 2 4 2 5 2 6 2 7  > test_settori.out

case $? in
	0) test_out=`echo test_settori.out`; echo out :  $test_out ;;
	1) ;;
	255);;
esac
