#!/bin/bash

#
# Creazione funzioni per Wella-SAP
#

#
# default values
#
DATABASE_NAME=sap
DATABASE_HOST=database

echo 'DB Configuration : sap'
echo -n 'Nome Database ['$DATABASE_NAME'] ? : '
read DB_NAME
echo -n 'Nome Host ['$DATABASE_HOST'] ? : '
read DB_HOST

if [ a"$DB_NAME" != a''  ]
then
DATABASE_NAME=$DB_NAME
fi

if [ a"$DB_HOST" != a''  ]
then
DATABASE_HOST=$DB_HOST
fi


echo `date` > funzioni.out
echo "CREATE FUNCTION isola(bpchar) returns text as 'select substr(\$1,1,1)' language 'sql';" | psql -h $DATABASE_HOST $DATABASE_NAME >> funzioni.out 2>&1 ; echo -n .
echo "CREATE FUNCTION settore(bpchar) returns text as 'select substr(\$1,2,2)' language 'sql';" | psql -h $DATABASE_HOST $DATABASE_NAME >> funzioni.out 2>&1 ; echo -n .

echo "CREATE FUNCTION ubicazione(bpchar) returns text as 'select substr(\$1,1,1)||\'.\'||substr(\$1,2,2)||\'.\'||substr(\$1,3,4)' language 'sql';" | psql -h $DATABASE_HOST $DATABASE_NAME >> funzioni.out 2>&1 ; echo -n .

