#!/bin/bash

#
# Creazione tabelle / indici / sequenze / funzioni
#

#
# default values
#
DATABASE_NAME=`cat ../doc/BASE_NAME`
DATABASE_HOST=`cat ../doc/DATABASE_HOST`

echo 'Creazione Tabelle'
echo -n 'Nome Database ['$DATABASE_NAME'] ? : '
read DB_NAME
echo -n 'Nome Host ['$DATABASE_HOST'] ? : '
read DB_HOST

if [ a"$DB_NAME" != a''  ]
then
DATABASE_NAME=$DB_NAME
fi

if [ a"$DB_HOST" != a''  ]
then
DATABASE_HOST=$DB_HOST
fi

echo 'Database Host = '$DB_HOST

# implementazione amazon 14-06-2019

dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/dett_colli.cfg         -t  dett_colli          > crea_tabelle.out 2>&1 ; echo -n .

dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/ordini_bertello.cfg    -t  ordini_bertello     >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/colli_bertello.cfg     -t  colli_bertello      >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/righe_bertello.cfg     -t  righe_bertello      >> crea_tabelle.out 2>&1 ; echo -n .

dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/ric_ord.cfg     -t ric_ord      >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/ric_art.cfg     -t ric_art      >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/ord_prod.cfg    -t ord_prod     >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/col_prod.cfg    -t col_prod     >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/rig_prod.cfg    -t rig_prod     >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/rig_prod.cfg    -t rig_tmp      >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/ubicazioni.cfg  -t ubicazioni   >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/articoli.cfg    -t articoli     >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/imballi.cfg     -t imballi      >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/errori_prelievo.cfg     -t errori_prelievo      >> crea_tabelle.out 2>&1 ; echo -n .

# tabelle di storico
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/ric_ord.cfg    -t ric_stor    >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/ord_prod.cfg   -t ord_stor    >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/col_prod.cfg   -t col_stor    >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/rig_prod.cfg   -t rig_stor    >> crea_tabelle.out 2>&1 ; echo -n .

# rm 13-04-2010 : Tabelle per gestione msg plc
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/plc_msg.cfg -t plc_msg                     >> crea_tabelle.out 2>&1 ; echo -n .
dbf2sql -h $DATABASE_HOST -d $DATABASE_NAME -c ../data_sap/plc_msg_history.cfg -t plc_msg_history     >> crea_tabelle.out 2>&1 ; echo -n .

echo 'CREATE SEQUENCE progcollo increment 1 minvalue 999999 maxvalue 2000000 start 1000000;' | psql -h $DATABASE_HOST $DATABASE_NAME >> crea_tabelle.out 2>&1 ; echo -n
echo 'CREATE SEQUENCE progcollo_add increment -1 minvalue 1000000 maxvalue 2000000 start 1999999;' | psql -h $DATABASE_HOST $DATABASE_NAME >> crea_tabelle.out 2>&1 ; echo -n
echo 'CREATE SEQUENCE sequence_anno increment 1 minvalue 2000 maxvalue 4000 start 2000;' | psql -h $DATABASE_HOST $DATABASE_NAME >> crea_tabelle.out 2>&1 ; echo -n

# registro badge
cat create_table_registro_badge.sql | psql -h $DATABASE_HOST $DATABASE_NAME >> crea_tabelle.out 2>&1 ; echo -n

echo "CREATE FUNCTION data_ora(timestamp) returns text as 'select data(\$1)||'' ''||ora(\$1)' language 'sql';" | psql -h $DATABASE_HOST $DATABASE_NAME >> crea_tabelle.out 2>&1 ; echo -n .

