drop index articoli_prcdpro;
drop index col_prod_cpnmcol;
drop index col_prod_key;
drop index col_prod_ordprog;
drop index col_stor_key;
drop index col_stor_ordprog;
drop index imballi_codimb;
drop index ord_prod_ordkey;
drop index ord_prod_ordprog;
drop index ord_stor_ordkey;
drop index ord_stor_ordprog;
drop index ric_art_ordprog;
drop index ric_ord_key;
drop index ric_stor_key;
drop index rig_prod_key;
drop index rig_prod_ordprog;
drop index rig_stor_key;
drop index rig_stor_ordprog;
drop index rig_tmp_key;
drop index rig_tmp_ordprog;
drop index ubicazioni_prodotto;
drop index ubicazioni_ubicazione;

create unique index articoli_prcdpro on articoli(prcdpro);
create index col_prod_cpnmcol on col_prod(cpnmcol);
create index col_prod_key on col_prod(ordkey);
create index col_prod_ordprog on col_prod(ordprog);
create index col_stor_key on col_stor(ordkey);
create index col_stor_ordprog on col_stor(ordprog);
create index imballi_codimb on imballi(codice);
create unique index ord_prod_ordkey on ord_prod(ordkey);
create index ord_prod_ordprog on ord_prod(ordprog);
create unique index ord_stor_ordkey on ord_stor(ordkey);
create index ord_stor_ordprog on ord_stor(ordprog);
create index ric_art_ordprog on ric_art(ordprog);
create unique index ric_ord_key on ric_ord(ordprog);
create index ric_stor_key on ric_stor(ordprog);
create index rig_prod_key on rig_prod(ordkey);
create index rig_prod_ordprog on rig_prod(ordprog);
create index rig_stor_key on rig_stor(ordkey);
create index rig_stor_ordprog on rig_stor(ordprog);
create index rig_tmp_key on rig_tmp(ordkey);
create index rig_tmp_ordprog on rig_tmp(ordprog);
create index ubicazioni_prodotto on ubicazioni(codprod);
create unique index ubicazioni_ubicazione on ubicazioni(ubicazione);
