drop table lista_letture_rese;
-- SMISTAMENTO TOTALLE RAGGRUPPATO PER GIORNO
--create table lista_letture_rese as select to_char(lptmlet,'YYYY-MM-DD') as "Giorno",sum(lpqtlet) as "copie" from rese_letture_prodotti  where lpstato!='S' and lptplet='S' group by to_char(lptmlet,'YYYY-MM-DD') order by to_char(lptmlet,'YYYY-MM-DD');
-- Smistamento per stazione
--create table lista_letture_rese as select to_char(lptmlet,'YYYY-MM-DD HH24') as "Ora_Lettura",lpnmstz,sum(lpqtlet) as "copie" from rese_letture_prodotti where lpstato!='S' and lptplet='S' and to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS')>'2013-04-10 11-00-01' group by to_char(lptmlet,'YYYY-MM-DD HH24'),lpnmstz order by to_char(lptmlet,'YYYY-MM-DD HH24'),lpnmstz;
-- SMISTAMENTO TOTALE
--create table lista_letture_rese as select lpcdean as "Barcode",lpad(lpnmres,6,'0') as "Reso",lpcdcli as "Cliente",lpqtlet as "Quantita",lpcdfor as "Fornitore", lplabel as "Label",to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS') as "Time_Lettura",to_char(lptmlet,'YYYY-MM-DD') as "Data_Lettura",to_char(lptmlet,'HH24') as "Ora_Lettura",to_char(lptmlet,'MI') as "Minuto_Lettura",lpnmstz from rese_letture_prodotti as "Num. Stazione"  where lpstato!='S' and lptplet='S' order by lpprlet;
-- SMISTAMENTO
--create table lista_letture_rese as select lpcdean as "Barcode",lpad(lpnmres,6,'0') as "Reso",lpcdcli as "Cliente",lpqtlet as "Quantita",lpcdfor as "Fornitore", lplabel as "Label",to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS') as "Time_Lettura",to_char(lptmlet,'YYYY-MM-DD') as "Data_Lettura",to_char(lptmlet,'HH24') as "Ora_Lettura",to_char(lptmlet,'MI') as "Minuto_Lettura",lpnmstz from rese_letture_prodotti as "Num. Stazione"  where lpstato!='S' and lptplet='S' and to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS')>'2013-04-02 06-00-01' and to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS')<'2013-04-03 06-00-00' order by lpprlet;
-- VENTILAZIONE
--create table lista_letture_rese as select lpcdean as "Barcode",lpad(lpnmres,6,'0') as "Reso",lpcdcli as "Cliente",lpqtlet as "Quantita",lpcdfor as "Fornitore", lplabel as "Label",to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS') as "Time_Lettura",to_char(lptmlet,'YYYY-MM-DD') as "Data_Lettura",to_char(lptmlet,'HH24') as "Ora_Lettura",to_char(lptmlet,'MI') as "Minuto_Lettura",lpnmstz from rese_letture_prodotti as "Num. Stazione"  where lpstato!='S' and lptplet='V' and to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS')>'2013-04-02 16-00-01' and to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS')<'2013-04-02 19-00-00' order by lpprlet;
-- VENTILAZIONE: COPIE PER STAZIONE ALL'ORA
--create table lista_letture_rese as select to_char(lptmlet,'YYYY-MM-DD HH24') as "Ora_Lettura",lpnmstz,sum(lpqtlet) as "copie" from rese_letture_prodotti where lpstato!='S' and lptplet='V' and to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS')>'2013-04-02 16-00-01' and to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS')<'2013-04-03 20-00-00' group by to_char(lptmlet,'YYYY-MM-DD HH24'),lpnmstz order by to_char(lptmlet,'YYYY-MM-DD HH24'),lpnmstz;
-- RESO E CLIENTE SPECIFICI
--create table lista_letture_rese as select lpcdcli as "Cliente",lpad(lpnmres,6,'0') as "Reso",lpdtres as "Data_reso",lpcdean as "Barcode",lpqtlet as "Quantita",lpcdfor as "Fornitore", lplabel as "Label",to_char(lptmlet,'YYYY-MM-DD HH24-MI-SS') as "Time_Lettura",to_char(lptmlet,'YYYY-MM-DD') as "Data_Lettura",to_char(lptmlet,'HH24') as "Ora_Lettura",to_char(lptmlet,'MI') as "Minuto_Lettura",lpnmstz as "Stazione",lpprcol as "Progr.Collo" from rese_letture_prodotti as "Num. Stazione"  where lpstato!='S' and lptplet='S'  and lpad(lpcdcli,6,'0')='004700' and lpad(lpnmres,6,'0')='000118' order by lpprlet;
create table lista_letture_rese as select to_char(lptmlet,'YYYY-MM') as "ANNO-MESE",sum(lpqtlet) as "copie" from rese_letture_prodotti where lpstato!='S' and lptplet='S'  group by to_char(lptmlet,'YYYY-MM') order by to_char(lptmlet,'YYYY-MM');

select * from lista_letture_rese;
